#ifndef SPIDER_VERSIONING_H
#define SPIDER_VERSIONING_H

#define SPIDER_VERSION_MAJOR  3
#define SPIDER_VERSION_MINOR  1
#define SPIDER_VERSION_STRING "3.1"

#define SPIDER_MAGIC          0xB31A

#endif // SPIDER_VERSIONING_H
